#Database
MYSQL_USERNAME: root
MYSQL_PASSWORD: root
MYSQL_HOST: localhost
MYSQL_PORT: 3306
MYSQL_DB: blogging_api

#Server
SERVER_PORT: 8080
ACTIVE_PROFILE: dev

#Email Config
EMAIL_HOST: smtp.gmail.com
EMAIL_PORT: 587
EMAIL_ID: chauhan775386@gmail.com
EMAIL_PASSWORD: rbil glhr wzgt fhnb
VERIFY_EMAIL_HOST: http://localhost:${SERVER_PORT}